---
title: Joe Shoop
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: project
sass:
  sass_dir: "/r/css/_scss/"
exclude:
- Gemfile
- Gemfile.lock
