title: "Joe Shoop"

sass:
    sass_dir: /r/css/_scss/

collections:
  projects:
    output: true
    permalink: /work/:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "project"
